steps:

# Clone repo to Cloud Build environment
- name: 'gcr.io/cloud-builders/git'
  args: ['clone',
  '${_REPO_URL}',
  '--verbose']
  id: 'Clone Repository'

# Run unit tests
- name: 'python:3.6-slim-jessie'
  entrypoint: 'bash'
  args: ['test/tests.sh']
  dir: 'src'
  id: 'Run Unit Tests'

  # Create the image for the MNIST component
- name: 'gcr.io/cloud-builders/docker'
  args: ['build',
         '-t', 'gcr.io/$_PROJECT_ID/mnist:${_TAG}', '.']
  dir: 'src/mnist'
  id: 'Building MNIST Image'
  waitFor: ['Run Unit Tests']